In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

s = Series([10, 20, 30], index=['a', 'b', 'c'])
df = pd.DataFrame(s, columns=["A"])

print(s.__class__)
print(type(df))

print(s.to_numpy())
print(df.to_numpy())

print(df.to_numpy().shape)

print(s.index)
print(df.index)
print(df.columns)

print(df)

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
[10 20 30]
[[10]
 [20]
 [30]]
(3, 1)
Index(['a', 'b', 'c'], dtype='object')
Index(['a', 'b', 'c'], dtype='object')
Index(['A'], dtype='object')
    A
a  10
b  20
c  30


In [2]:
# make dataframe using dictionary and matrix
d = {'one' : Series([1,2],index={'a', 'b'}),
    'two' : Series([1,2,3], index={'a','b','c'})}
df = pd.DataFrame(d)
print(df)


x = np.arange(4).reshape((2,2))
print(x)
df = pd.DataFrame(x)
df.columns=['A', 'B']
df.index=[11,12]
print(x)
print(df)


   one  two
a  1.0    1
b  2.0    2
c  NaN    3
[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
    A  B
11  0  1
12  2  3


In [4]:
import statsmodels.api as sm

trees = sm.datasets.get_rdataset("trees")['data']


In [5]:
trees.head()

Girth  Height  Volume
0    8.3      70    10.3
1    8.6      65    10.3
2    8.8      63    10.2
3   10.5      72    16.4
4   10.7      81    18.8

In [6]:
mtcars = sm.datasets.get_rdataset("mtcars")['data']
iris = sm.datasets.get_rdataset("iris")['data']

In [17]:
s1 = pd.Series([1.0, 2, 3])
sa = pd.Series([1.0, 2, 3], index=['a','b','c'])
sc = pd.Series([0, 1, 2], index=['a', 'b', 'd'])
sn = pd.Series([1.2, 1.3, 3.3, 5, 3,4])

In [18]:
s1

0    1.0
1    2.0
2    3.0
dtype: float64

In [19]:
s1-2

0   -1.0
1    0.0
2    1.0
dtype: float64

In [20]:
sa

a    1.0
b    2.0
c    3.0
dtype: float64

In [21]:
sc

a    0
b    1
d    2
dtype: int64

In [22]:
sac = sa+sc

In [23]:
sac

a    1.0
b    3.0
c    NaN
d    NaN
dtype: float64

In [24]:
# Series 결측치 NaN 처리
s1 = pd.Series([1.0, 2, 3])
sa = pd.Series([1.0, 2, 3], index=['a','b','c'])
sc = pd.Series([0.0,1,2], index=['a', 'b', 'c'])
sn = pd.Series([1, 2, 1, 3, 3, 5, 3, 4])
print(sn)

0    1
1    2
2    1
3    3
4    3
5    5
6    3
7    4
dtype: int64


In [25]:
sn.head()

0    1
1    2
2    1
3    3
4    3
dtype: int64

In [26]:
sn.describe()

count    8.00000
mean     2.75000
std      1.38873
min      1.00000
25%      1.75000
50%      3.00000
75%      3.25000
max      5.00000
dtype: float64

In [28]:
sn.nunique()

5